# -*- coding: utf-8 -*-
"""chatbot_chatterbot.ipynb

Automatically generated by Colaboratory.

"""

!pip install chatterbot

!pip install chatterbot_corpus

from chatterbot import ChatBot
bot=ChatBot("Buddy",storage_adapter='chatterbot.storage.SQLStorageAdapter',database_uri='sqlite:///database.sqlite3')

from chatterbot.trainers import ListTrainer
train=ListTrainer(bot)

train.train(['Hi',
'Hello',
'I need your assistance regarding my order',
'Please, Provide me with your order id',
'I have a complaint.',
'Please elaborate, your concern',
'How long it will take to receive an order ?',
'An order takes 3-5 Business days to get delivered.',
'Okay Thanks',
'No Problem! Have a Good Day!'])

print(bot.get_response('I want the details of my order'))

"""<h2> To Be Continued <h2>
<h3> More to be done with Tensorflow,pickle,lstm and with more training data <h3>
"""

